config/routes.rb
Rails.application.routes.draw do
  resources :articles
  resources :healths
  resources :comments
  resources :tracks
  devise_for :users

  get '/index', to: 'home#index'
  root :to => "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/health.rb
class Health < ApplicationRecord
  belongs_to :user
end

app/controllers/healths_controller.rb
class HealthsController < ApplicationController
  before_action:authenticate_user!
  before_action :set_health, only: [:show, :edit, :update, :destroy]

  # GET /healths
  # GET /healths.json
  def index
    @healths = Health.all
  end

  # GET /healths/1
  # GET /healths/1.json
  def show
  end

  # GET /healths/new
  def new
    @health = Health.new
  end

  # GET /healths/1/edit
  def edit
  end

  # POST /healths
  # POST /healths.json
  def create
    params[:health][:user_id] = current_user.id
    @health = Health.new(health_params)

    respond_to do |format|
      if @health.save
        format.html { redirect_to @health, notice: 'Health was successfully created.' }
        format.json { render :show, status: :created, location: @health }
      else
        format.html { render :new }
        format.json { render json: @health.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /healths/1
  # PATCH/PUT /healths/1.json
  def update
    respond_to do |format|
      params[:health][:user_id] = current_user.id
      if @health.update(health_params)
        format.html { redirect_to @health, notice: 'Health was successfully updated.' }
        format.json { render :show, status: :ok, location: @health }
      else
        format.html { render :edit }
        format.json { render json: @health.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /healths/1
  # DELETE /healths/1.json
  def destroy
    @health.destroy
    respond_to do |format|
      format.html { redirect_to healths_url, notice: 'Health was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_health
      @health = Health.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def health_params
      params.require(:health).permit(:target, :exercise, :birthday, :weight, :height, :step, :user_id)
    end
end

app/helpers/healths_helper.rb
module HealthsHelper
end

app/views/healths/_form.html.erb
<%= form_with(model: health, local: true) do |form| %>
  <% if health.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(health.errors.count, "error") %> prohibited this health from being saved:</h2>

      <ul>
      <% health.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :target %>
    <%= form.text_field :target %>
  </div>

  <div class="field">
    <%= form.label :exercise %>
    <%= form.text_field :exercise %>
  </div>

  <div class="field">
    <%= form.label :birthday %>
    <%= form.date_select :birthday %>
  </div>

  <div class="field">
    <%= form.label :weight %>
    <%= form.number_field :weight %>
  </div>

  <div class="field">
    <%= form.label :height %>
    <%= form.number_field :height %>
  </div>

  <div class="field">
    <%= form.label :step %>
    <%= form.number_field :step %>
  </div>

  <div class="field hidden">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/healths/edit.html.erb
<h1>Editing Health</h1>

<%= render 'form', health: @health %>

<%= link_to 'Show', @health %> |
<%= link_to 'Back', healths_path %>

app/views/healths/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Healths</h1>

<table>
  <thead>
    <tr>
      <th>Target</th>
      <th>Exercise</th>
      <th>Birthday</th>
      <th>Weight</th>
      <th>Height</th>
      <th>Step</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @healths.each do |health| %>
      <tr>
        <td><%= health.target %></td>
        <td><%= health.exercise %></td>
        <td><%= health.birthday %></td>
        <td><%= health.weight %></td>
        <td><%= health.height %></td>
        <td><%= health.step %></td>
        <td><%= health.user.email %></td>
        <td><%= link_to 'Show', health %></td>
        <td><%= link_to 'Edit', edit_health_path(health) %></td>
        <td><%= link_to 'Destroy', health, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Health', new_health_path %>

app/views/healths/new.html.erb
<h1>New Health</h1>

<%= render 'form', health: @health %>

<%= link_to 'Back', healths_path %>

app/views/healths/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Target:</strong>
  <%= @health.target %>
</p>

<p>
  <strong>Exercise:</strong>
  <%= @health.exercise %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @health.birthday %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @health.weight %>
</p>

<p>
  <strong>Height:</strong>
  <%= @health.height %>
</p>

<p>
  <strong>Step:</strong>
  <%= @health.step %>
</p>

<p>
  <strong>User:</strong>
  <%= @health.user.email %>
</p>

<%= link_to 'Edit', edit_health_path(@health) %> |
<%= link_to 'Back', healths_path %>